# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b11a29fb42351cb11b577a24e1f4af1e41049449db9cf8b80fe1771ea684e677c77eb4e5f0783647826c6638967c502b92401481d9e68f165ac4f94446d2610d

test:
  secret_key_base: 5a2de58f907d19c076c46e16067785ba8ad83f60e91b117b7a9da3c63cc5046d329b32c475a3ec91fc9205359a24bc0ef559aa652f94aa874b31e17e6c6ce59d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
